name: ci

on:
  push:
    branches: master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ secrets.CR_USERNAME }} --password-stdin
      - name: Build
        run: docker build -t ghcr.io/${{ secrets.CR_USERNAME }}/vet-clinic-api:latest .
      - name: Push
        run: docker image push ghcr.io/${{ secrets.CR_USERNAME }}/vet-clinic-api:latest
